version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: countries_postgres
    environment:
      POSTGRES_DB: coutries_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: countries_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/coutries_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.xml
    ports:
      - "8080:8080"
    restart: always

volumes:
  pg_data:
